import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React, { ReactNode } from 'react';
import { PrimeReactProvider } from 'primereact/api';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <PrimeReactProvider>
            <html lang="en">
                <body className={inter.className}>{children}</body>
            </html>
        </PrimeReactProvider>
    );
}
